version: "3.8"

services:
  # === Download Stack ===
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${QBIT_PORT:-8080}:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${NORDVPN_COUNTRY}
      - FIREWALL=on
      - DOT=off
      - LOG_LEVEL=info
      - UPDATER_PERIOD=24h
      - HEALTH_TARGET_ADDRESS=1.1.1.1:443
      - HEALTH_READ_TIMEOUT=2s
      - HEALTH_WAIT_DURATION=10s
    volumes:
      - ${CONFIG_DIR:-./config}/gluetun:/gluetun
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--dns-timeout=2", "--connect-timeout=2", "https://1.1.1.1/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - flame.type=app
      - flame.name=Gluetun VPN
      - flame.url=http://${HOST_IP}:${QBIT_PORT:-8080}
      - flame.icon=vpn

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBIT_PORT:-8080}
    volumes:
      - ${BASE_PATH}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads:cached
    restart: unless-stopped
    depends_on:
      - gluetun
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${QBIT_PORT:-8080}/api/v2/app/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=qBittorrent
      - flame.url=http://${HOST_IP}:${QBIT_PORT:-8080}
      - flame.icon=download

  # === Media Management ===
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/prowlarr:/config
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Prowlarr
      - flame.url=http://${HOST_IP}:${PROWLARR_PORT:-9696}
      - flame.icon=router-network-wireless

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/sonarr:/config
      - ${MEDIA_SHARE}:/media:cached
      - ${DOWNLOAD_DIR}:/downloads:cached
    ports:
      - "${SONARR_PORT:-8989}:8989"
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Sonarr
      - flame.url=http://${HOST_IP}:${SONARR_PORT:-8989}
      - flame.icon=television-classic

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/radarr:/config
      - ${MEDIA_SHARE}:/media:cached
      - ${DOWNLOAD_DIR}:/downloads:cached
    ports:
      - "${RADARR_PORT:-7878}:7878"
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Radarr
      - flame.url=http://${HOST_IP}:${RADARR_PORT:-7878}
      - flame.icon=video-vintage

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/bazarr:/config
      - ${MEDIA_SHARE}:/media:cached
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Bazarr
      - flame.url=http://${HOST_IP}:${BAZARR_PORT:-6767}
      - flame.icon=subtitles-outline

  # === Media Servers ===
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - PLEX_DEBUG=1
      - PLEX_MEDIA_SERVER_USE_SYSLOG=true
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${MEDIA_SHARE}/tv:/tv:ro,cached
      - ${MEDIA_SHARE}/movies:/movies:ro,cached
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    privileged: true
    labels:
      - flame.type=app
      - flame.name=Plex
      - flame.url=http://${HOST_IP}:32400/web
      - flame.icon=plex

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_CONFIG_DIR=/config/config
      - JELLYFIN_DATA_DIR=/config
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_LOG_DIR=/config/log
    volumes:
      - ${BASE_PATH}/jellyfin/config:/config
      - ${BASE_PATH}/jellyfin/cache:/cache
      - ${MEDIA_SHARE}/tv:/tv:ro,cached
      - ${MEDIA_SHARE}/movies:/movies:ro,cached
      - ${MEDIA_SHARE}/music:/music:ro,cached
      - ${MEDIA_SHARE}/system:/system:ro,cached
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
      - "7359:7359/udp"  # Local network discovery
      - "1900:1900/udp"  # DLNA
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Jellyfin
      - flame.url=http://${HOST_IP}:${JELLYFIN_PORT:-8096}
      - flame.icon=jellyfish-outline

  # === Optional Services ===
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    ports:
      - "${FLARESOLVERR_PORT:-8191}:8191"
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=FlareSolverr
      - flame.url=http://${HOST_IP}:${FLARESOLVERR_PORT:-8191}
      - flame.icon=puzzle

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/overseerr:/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Overseerr
      - flame.url=http://${HOST_IP}:${OVERSEERR_PORT:-5055}
      - flame.icon=list-box-outline

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - UI_PORT=${MAINTAINERR_PORT:-6246}
      - API_PORT=${MAINTAINERR_API_PORT:-3001}
    volumes:
      - ${BASE_PATH}/maintainerr:/opt/data:rw
    ports:
      - "${MAINTAINERR_PORT:-6246}:6246"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${MAINTAINERR_PORT:-6246}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - flame.type=app
      - flame.name=Maintainerr
      - flame.url=http://${HOST_IP}:${MAINTAINERR_PORT:-6246}
      - flame.icon=trash-can-outline

  recyclarr:
    image: recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      - TZ=${TZ}
    volumes:
      - recyclarr_config:/config
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Recyclarr
      - flame.url=http://${HOST_IP}
      - flame.icon=recycle

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${FLAME_PASSWORD:-flame}
    volumes:
      - ${BASE_PATH}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${FLAME_PORT:-5005}:5005"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5005"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - flame.type=app
      - flame.name=Flame
      - flame.url=http://${HOST_IP}:${FLAME_PORT:-5005}
      - flame.icon=fire

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/filebrowser/database:/database
      - ${BASE_PATH}/filebrowser/config:/config
      - ${FILEBROWSER_ROOT}:/srv/media:ro
      - ${DOWNLOAD_DIR}:/srv/downloads
    ports:
      - "${FILEBROWSER_PORT:-8090}:80"
    networks:
      - media_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: --database /database/filebrowser.db --config /config/filebrowser.json
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      - flame.type=app
      - flame.name=File Browser
      - flame.url=http://${HOST_IP}:${FILEBROWSER_PORT:-8090}
      - flame.icon=folder

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - NETDATA_RUNTIME_MEMORY_MODE=dbengine
      - NETDATA_UPDATE_EVERY=5
      - NETDATA_HISTORY_DAYS=7
      - NETDATA_MONITORING_DISKS=/dev/sd*,/mnt/showtime
      - NETDATA_MONITORING_SERVICES=plex*,jellyfin*,qbittorrent*,sonarr*,radarr*
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/showtime:/host/mnt/showtime:ro
    labels:
      - flame.type=app
      - flame.name=Netdata
      - flame.url=http://${HOST_IP}:19999
      - flame.icon=monitor

# === Transcoding Services ===
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - media_net
    ports:
      - "${TDARR_WEB_PORT:-8265}:8265"  # webUI port
      - "${TDARR_SERVER_PORT:-8266}:8266"  # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - serverIP=0.0.0.0
      - serverPort=${TDARR_SERVER_PORT:-8266}
      - webUIPort=${TDARR_WEB_PORT:-8265}
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=kynes-internal
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${BASE_PATH}/tdarr/server:/app/server
      - ${BASE_PATH}/tdarr/configs:/app/configs
      - ${BASE_PATH}/tdarr/logs:/app/logs
      - ${MEDIA_SHARE}:/media:cached
      - ${BASE_PATH}/tdarr/cache:/temp
    devices:
      - /dev/dri:/dev/dri    # For QuickSync support
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8265"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - flame.type=app
      - flame.name=Tdarr
      - flame.url=http://${HOST_IP}:${TDARR_WEB_PORT:-8265}
      - flame.icon=transfer

volumes:
  recyclarr_config:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  media_net:
    driver: bridge
