version: "3.8"

x-common-vars: &common-vars
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

services:
  # === Download Stack ===
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${QBIT_PORT:-8080}:8080"
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL=on
      - DOT=off
      - LOG_LEVEL=info
      - UPDATER_PERIOD=24h
      - HEALTH_TARGET_ADDRESS=1.1.1.1:443
      - HEALTH_READ_TIMEOUT=2s
      - HEALTH_WAIT_DURATION=10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    volumes:
      - ${CONFIG_DIR:-./config}/gluetun:/gluetun
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--dns-timeout=2", "--connect-timeout=2", "https://1.1.1.1/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      <<: *common-vars
      - WEBUI_PORT=${QBIT_PORT:-8080}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
    volumes:
      - ${BASE_PATH}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads:cached
    restart: unless-stopped
    depends_on:
      - gluetun

  # === Media Management ===
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *common-vars
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 150M
    volumes:
      - ${BASE_PATH}/prowlarr:/config
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    networks:
      - media_net
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      <<: *common-vars
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 350M
    volumes:
      - ${BASE_PATH}/sonarr:/config
      - ${MEDIA_SHARE}:/media:cached
      - ${DOWNLOAD_DIR}:/downloads:cached
    ports:
      - "${SONARR_PORT:-8989}:8989"
    networks:
      - media_net
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      <<: *common-vars
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 350M
    volumes:
      - ${BASE_PATH}/radarr:/config
      - ${MEDIA_SHARE}:/media:cached
      - ${DOWNLOAD_DIR}:/downloads:cached
    ports:
      - "${RADARR_PORT:-7878}:7878"
    networks:
      - media_net
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      <<: *common-vars
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    volumes:
      - ${BASE_PATH}/bazarr:/config
      - ${MEDIA_SHARE}:/media:cached
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    networks:
      - media_net
    restart: unless-stopped

  # === Media Servers ===
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      <<: *common-vars
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${MEDIA_SHARE}/tv:/tv:ro,cached
      - ${MEDIA_SHARE}/movies:/movies:ro,cached
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      <<: *common-vars
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    volumes:
      - ${BASE_PATH}/jellyfin/config:/config
      - ${BASE_PATH}/jellyfin/cache:/cache
      - ${MEDIA_SHARE}/movies:/movies:ro,cached
      - ${MEDIA_SHARE}/tv:/tv:ro,cached
    restart: unless-stopped

  # === Optional Services with Reduced Resources ===
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 150M
    ports:
      - "8191:8191"
    networks:
      - media_net
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      <<: *common-vars
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    volumes:
      - ${BASE_PATH}/overseerr:/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    networks:
      - media_net
    restart: unless-stopped

  recyclarr:
    image: recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      - TZ=${TZ}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
    volumes:
      - recyclarr_config:/config
    networks:
      - media_net
    restart: unless-stopped

volumes:
  recyclarr_config:

networks:
  media_net:
    driver: bridge
