version: "3.8"

services:
  # === Download Stack ===
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${QBIT_PORT:-8080}:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - FIREWALL=on
      - DOT=off
      - LOG_LEVEL=info
      - UPDATER_PERIOD=24h
      - HEALTH_TARGET_ADDRESS=1.1.1.1:443
      - HEALTH_READ_TIMEOUT=2s
      - HEALTH_WAIT_DURATION=10s
    volumes:
      - ${CONFIG_DIR:-./config}/gluetun:/gluetun
    networks:
      - media_net
    restart: unless-stopped
    mem_limit: 256M
    memswap_limit: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "--retry", "3", "http://localhost:${QBIT_PORT:-8080}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - flame.type=app
      - flame.name=Gluetun VPN
      - flame.url=http://${HOST_IP}:${QBIT_PORT:-8080}
      - flame.icon=vpn
 
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBIT_PORT:-8080}
    volumes:
      - ${BASE_PATH}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads:cached
    restart: unless-stopped
    mem_limit: 1024M
    memswap_limit: 1536M
    depends_on:
      - gluetun
    healthcheck:
      test: ["CMD", "curl", "-f", "--retry", "3", "http://localhost:${QBIT_PORT:-8080}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - flame.type=app
      - flame.name=qBittorrent
      - flame.url=http://${HOST_IP}:${QBIT_PORT:-8080}
      - flame.icon=download

  # === Media Management ===
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/prowlarr:/config
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:9696/prowlarr/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Prowlarr
      - flame.url=http://${HOST_IP}:${PROWLARR_PORT:-9696}
      - flame.icon=plus-network-outline

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/sonarr:/config
      - ${MEDIA_SHARE}:/media:cached
      - ${DOWNLOAD_DIR}:/downloads:cached
    ports:
      - "${SONARR_PORT:-8989}:8989"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:8989/sonarr/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Sonarr
      - flame.url=http://${HOST_IP}:${SONARR_PORT:-8989}
      - flame.icon=television-classic

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/radarr:/config
      - ${MEDIA_SHARE}:/media:cached
      - ${DOWNLOAD_DIR}:/downloads:cached
    ports:
      - "${RADARR_PORT:-7878}:7878"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:7878/radarr/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Radarr
      - flame.url=http://${HOST_IP}:${RADARR_PORT:-7878}
      - flame.icon=video-vintage

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/bazarr:/config
      - ${MEDIA_SHARE}:/media:cached
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:6767/bazarr/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Bazarr
      - flame.url=http://${HOST_IP}:${BAZARR_PORT:-6767}
      - flame.icon=subtitles-outline

  # === Media Servers ===
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - PLEX_DEBUG=1
      - PLEX_MEDIA_SERVER_USE_SYSLOG=true
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${MEDIA_SHARE}/tv:/tv:ro,cached
      - ${MEDIA_SHARE}/movies:/movies:ro,cached
      - ${MEDIA_SHARE}/system:/system:ro,cached
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:32400/identity"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    privileged: true
    labels:
      - flame.type=app
      - flame.name=Plex
      - flame.url=http://${HOST_IP}:32400/web
      - flame.icon=plex

  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # Add these to handle the migration issue
      - FLASK_ENV=production
      - WIZARR_SKIP_MIGRATION=${WIZARR_SKIP_MIGRATION:-false}
      - PYTHONPATH=/data
    volumes:
      - ${BASE_PATH}/wizarr/database:/data/database  
    ports:
      - "${WIZARR_PORT:-5690}:5690"
    networks:
      - media_net
    restart: unless-stopped
    # Updated command to handle the problematic migration
    command: >
      sh -c "
        # Check if the problematic migration file exists and remove it
        if [ -f /data/migrations/versions/20250729_squashed_connections_expiry_system.py ]; then
          echo 'Removing problematic migration file to prevent SQL errors...'
          rm -f /data/migrations/versions/20250729_squashed_connections_expiry_system.py
        fi &&
        # Initialize the app normally
        python /data/app.py
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:5690/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Wizarr
      - flame.url=http://${HOST_IP}:${WIZARR_PORT:-5690}
      - flame.icon=account-plus


  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/tautulli:/config
    ports:
      - "${TAUTULLI_PORT:-8181}:8181"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:8181/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Tautulli
      - flame.url=http://${HOST_IP}:${TAUTULLI_PORT:-8181}
      - flame.icon=chart-line
      
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_CONFIG_DIR=/config/config
      - JELLYFIN_DATA_DIR=/config
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_LOG_DIR=/config/log
    volumes:
      - ${BASE_PATH}/jellyfin/config:/config
      - ${BASE_PATH}/jellyfin/cache:/cache
      - ${MEDIA_SHARE}/tv:/tv:ro,cached
      - ${MEDIA_SHARE}/movies:/movies:ro,cached
      - ${MEDIA_SHARE}/music:/music:ro,cached
      - ${MEDIA_SHARE}/system:/system:ro,cached
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
      - "7359:7359/udp"  # Local network discovery
      - "1900:1900/udp"  # DLNA
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - flame.type=app
      - flame.name=Jellyfin
      - flame.url=http://${HOST_IP}:${JELLYFIN_PORT:-8096}
      - flame.icon=jellyfish-outline

  # === Optional Services ===
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 3 0 * * 6} 
      - WATCHTOWER_NOTIFICATION_REPORT=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${WATCHTOWER_PORT:-8081}:8080"
    networks:
      - media_net
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Watchtower
      - flame.url=http://${HOST_IP}:${WATCHTOWER_PORT:-8081}
      - flame.icon=update

      
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    ports:
      - "${FLARESOLVERR_PORT:-8191}:8191"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:8191/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=FlareSolverr
      - flame.url=http://${HOST_IP}:${FLARESOLVERR_PORT:-8191}
      - flame.icon=puzzle

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/overseerr:/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Overseerr
      - flame.url=http://${HOST_IP}:${OVERSEERR_PORT:-5055}
      - flame.icon=format-list-bulleted-triangle

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/jellyseerr:/app/config
    ports:
      - "${JELLYSEERR_PORT:-5056}:5055"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "--show-error", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - flame.type=app
      - flame.name=Jellyseerr
      - flame.url=http://${HOST_IP}:${JELLYSEERR_PORT:-5056}
      - flame.icon=jellyfish


  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - UI_PORT=${MAINTAINERR_PORT:-6246}
      - API_PORT=${MAINTAINERR_API_PORT:-3001}
    volumes:
      - ${BASE_PATH}/maintainerr:/opt/data:rw
    ports:
      - "${MAINTAINERR_PORT:-6246}:6246"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${MAINTAINERR_PORT:-6246}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - flame.type=app
      - flame.name=Maintainerr
      - flame.url=http://${HOST_IP}:${MAINTAINERR_PORT:-6246}
      - flame.icon=trash-can-outline

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${FLAME_PASSWORD:-flame}
    volumes:
      - ${BASE_PATH}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${FLAME_PORT:-1313}:5005"
    networks:
      - media_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5005"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - flame.type=app
      - flame.name=Flame
      - flame.url=http://${HOST_IP}:${FLAME_PORT:-5005}
      - flame.icon=fire

# === Transcoding Services ===
  fileflows:
    image: revenz/fileflows:25.06
    container_name: fileflows
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TempPathHost=/tmp/fileflows
    volumes:
      - ${BASE_PATH}/fileflows:/app/Data
      - /tmp:/temp
      - ${BASE_PATH}/fileflows/logs:/app/Logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MEDIA_SHARE}:/library:cached
    ports:
      - "${FILEFLOWS_PORT:-19200}:5000"
    networks:
      - media_net
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri    # For QuickSync support
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - flame.type=app
      - flame.name=FileFlows
      - flame.url=http://${HOST_IP}:${FILEFLOWS_PORT:-19200}
      - flame.icon=transfer

networks:
  media_net:
    driver: bridge
