version: "3.8"

services:
  # === Download Stack ===
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${QBIT_PORT:-8080}:8080"
    volumes:
      - ${BASE_PATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASS}
      - SERVER_COUNTRIES=${NORDVPN_COUNTRY:-Netherlands}
      - FIREWALL=on
      - DOT=off
    networks:
      - media_net
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    user: "99:101"  # Add this line
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBIT_PORT:-8080}
    volumes:
      - ${BASE_PATH}/qbittorrent:/config
      - ${DOWNLOAD_DIR:-/mnt/showtime/downloads}:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun

  # === Media Management ===
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/prowlarr:/config
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    networks:
      - media_net
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    user: "99:101"  # Add this line
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/sonarr:/config
      - ${MEDIA_SHARE:-/mnt/showtime}:/media
      - ${DOWNLOAD_DIR:-/mnt/showtime/downloads}:/downloads
    ports:
      - "${SONARR_PORT:-8989}:8989"
    networks:
      - media_net
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    user: "99:101"  # Add this line
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/radarr:/config
      - ${MEDIA_SHARE:-/mnt/showtime}:/media
      - ${DOWNLOAD_DIR:-/mnt/showtime/downloads}:/downloads
    ports:
      - "${RADARR_PORT:-7878}:7878"
    networks:
      - media_net
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/bazarr:/config
      - ${MEDIA_SHARE:-/mnt/showtime}:/media
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    networks:
      - media_net
    restart: unless-stopped

  # === Media Servers ===
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${MEDIA_SHARE:-/mnt/showtime}/tv:/tv
      - ${MEDIA_SHARE:-/mnt/showtime}/movies:/movies
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host  # Better for old hardware/transcoding
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/jellyfin/config:/config
      - ${BASE_PATH}/jellyfin/cache:/cache
      - ${MEDIA_SHARE:-/mnt/showtime}/movies:/movies
      - ${MEDIA_SHARE:-/mnt/showtime}/tv:/tv
    restart: unless-stopped

  # === Optional Services ===
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    ports:
      - "8191:8191"
    networks:
      - media_net
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/overseerr:/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    networks:
      - media_net
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${MEDIA_SHARE:-/mnt/showtime}:/share
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_KEY}
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_KEY}
    networks:
      - media_net
      
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - homarr_configs:/app/data/configs
      - homarr_icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${HOMARR_PORT:-7575}:7575
    environment:
      - TZ=${TZ}
    networks:
      - media_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7575/"]
      interval: 30s
      timeout: 10s
      retries: 3

  recyclarr:
    image: recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      - TZ=${TZ}
    volumes:
      - recyclarr_config:/config
    networks:
      - media_net
    restart: unless-stopped

  unmanic:
    image: josh5/unmanic:latest
    container_name: unmanic
    devices:
      - /dev/dri:/dev/dri # Hardware transcoding support (if available)
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UNMANIC_LIBRARY_PATH=/library # Don't change this
      - UNMANIC_CACHE_PATH=/tmp/unmanic # Don't change this
    volumes:
      - unmanic_config:/config
      - unmanic_cache:/tmp/unmanic
      - ${MEDIA_SHARE:-/mnt/showtime}:/library/media:rw
      # Add custom post-processing scripts directory if needed
      #- ${BASE_PATH}/unmanic/scripts:/scripts
    ports:
      - "${UNMANIC_PORT:-8888}:8888"
    networks:
      - media_net
    restart: unless-stopped

volumes:
  recyclarr_config:
  unmanic_config:
  unmanic_cache:
  homarr_configs:
  homarr_icons:

networks:
  media_net:
    driver: bridge
